language: ruby
bundler_args: --without development
rvm:
  - 2.1.0
env:
  - S3_BUCKET_NAME=marsbook_artifacts
  - RDS_DATABASENAME=interesting_images
  - RDS_USERNAME=marsbook
after_success:
  "bundle exec rake deploy"